### ISSUE TITLE
Bug status of connection

### ISSUE THREAD

**Issue by arsiesis** [Supergiovane/node-red-contrib-knx-ultimate#10]
Hi,
Found this little bug ...

> NODERED version : 0.20.8
> NODE.js version : v12.0.0
> node-red-contrib-knx-ultimate version : 1.1.10

Message that will appear in the console if the ip / knx router is disconnected from the IP network

**In debug console of nodered :** 

```

msg : error
"TypeError: node.setNodeStatus is not a function"


```

**In NPM console :**

```

TypeError: node.setNodeStatus is not a function
    at new knxUltimate (XXXX\node-red-contrib-knx-ultimate\knxUltimate.js:29:26)
    at Object.createNode (XXXX\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (XXXX\@node-red\runtime\lib\nodes\flows\Flow.js:176:44)
    at start (XXXX\node_modules\@node-red\runtime\lib\nodes\flows\index.js:329:33)
    at XXXX\@node-red\runtime\lib\nodes\flows\index.js:196:21
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by Supergiovane** [comment]
Thank you, will take a look
