### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by matteofranceschini** [Supergiovane/node-red-contrib-knx-ultimate#126]
**Salutation**
Hi there! Thank you for the great library! :D

**Describe the bug**
I'm actually not sure if it's a bug or not, but it's a strange behavior. Everything works fine and then, out of the blue, every knx-ultimate node continues to toggle between "undefined error" and "disconnected".

I "solved" the issue by connecting a notification to my phone when this happens, and i just restart all the flows and everything works again.

```
Trace: TypeError: Cannot read property 'knx_layer' of undefined
    at fsm.inbound_CONNECT_RESPONSE (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/FSM.js:163:76)
    at fsm.handle (/config/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:135:1)
    at fsm.Fsm.<computed> [as handle] (/config/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
    at fsm.onUdpSocketMessage (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/Connection.js:75:14)
    at Socket.<anonymous> (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/IpTunnelingConnection.js:46:12)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
    at consoleCall (<anonymous>)
    at fsm.onUdpSocketMessage (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/Connection.js:87:13)
    at Socket.<anonymous> (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/IpTunnelingConnection.js:46:12)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[error] 6/28/2021, 3:26:44 PM knxUltimate-config: connFailCb, Disconnected.
Trace: TypeError: Cannot read property 'knx_layer' of undefined
    at fsm.inbound_CONNECT_RESPONSE (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/FSM.js:163:76)
    at fsm.handle (/config/node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:135:1)
    at fsm.Fsm.<computed> [as handle] (/config/node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
    at fsm.onUdpSocketMessage (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/Connection.js:75:14)
    at Socket.<anonymous> (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/IpTunnelingConnection.js:46:12)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
    at consoleCall (<anonymous>)
    at fsm.onUdpSocketMessage (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/Connection.js:87:13)
    at Socket.<anonymous> (/config/node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/IpTunnelingConnection.js:46:12)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[error] 6/28/2021, 3:26:44 PM knxUltimate-config: connFailCb, **Disconnected.**
```

**To Reproduce**
Sadly, it just happens randomly on a weekly basis, but with no preferred day.

I might add that I run both knx-ultimate and the "standard" homeassistant knx integration in parallel with the same (siemens) knx bridge.

I noticed that there's a maximum number of concurrent connections that my bridge supports ( i cannot have homeassistant+ knxultimate + ETS and a second (for debugging) nodered instance all together: the fourth will be ignored and it cannot read the bus) and I'm not sure if this issue is due to this limit.

I must say that it's more than two months that I just have homeassistant and one instance of knx-ultimate in its nodered-addon, and I assume that the concurrent connections shall be just two, in this case.

**Expected behavior**
If it's a "concurrent connections" issue, ETS tells me "the bridge has rejected the connection because you have reached the limit", could it be possible to "gracefully" handle this error?

**Screenshots**
![image](https://user-images.githubusercontent.com/3541957/123644950-2bcacd00-d826-11eb-9d67-5bb9f1347121.png)
![image](https://user-images.githubusercontent.com/3541957/123644999-35eccb80-d826-11eb-99f0-fed0953be82f.png)

**Knx-Ultimate Version**
 - 1.2.32

**Are you running node-red behind homematic, docker or anything similar?**
 - In a docker managed by homeassistant addons.

**Additional context**
I can run any test, I have time try things and provide logs :)

**Comment by Supergiovane** [comment]
Ciao Matteo,
No this shouldn't happens.
Running two instances of KNX client on same machine is not supported (that means, having to deal with one IP and one shared port).
I also have homeassistant, but i run node-red on another VM.
I suggest you to install node-red on another PC (windows or linux doesn't matter) and test it. You'll see no errors on both.
If you're using an old siemens interface, please be aware that this has issues. I don't remember the model (Siemens n148 i think), but i hat to throw the Siemens interface in the trashcan, due to the poor KNX protocol implementation.
I suggest you to also check and enable the "Suppress ACK..." option in the knx-ultimate gateway config node.

**Comment by matteofranceschini** [comment]
uh, thank you! I'll definitively move the nodered instance to another VM then... I didn't know it may be an issue!

My Siemens interface is ~10yrs old I think, maybe it's the good time to change it :D

**Comment by Supergiovane** [comment]
If you change it, go buy a KNX Router instead if Interface. It cost a little more, but you have no connection limit!
Fammi sapere se poi funziona tutto. Ciao.
