### ISSUE TITLE
Node-red crashes on boot because it cannot connect to a KNX host

### ISSUE THREAD

**Issue by martijndierckx** [Supergiovane/node-red-contrib-knx-ultimate#172]
Hello there

I'm encountering an issue after updating Node-red and all my palette dependencies to the latest versions.

**Describe the bug**
Node-Red crashes after boot

```
node-red_1  | [error] 2/14/2022, 5:02:13 PM.902 knxUltimate-config: Disconnected by: connect ECONNREFUSED 192.168.8.186:3671
node-red_1  | [error] 2/14/2022, 5:02:33 PM.902 KNXUltimate-KNXEngine: Sending KNX packet: Send TCP sending error: Cannot call write after a stream was destroyed
node-red_1  | 14 Feb 17:02:33 - [red] Uncaught Exception:
node-red_1  | 14 Feb 17:02:33 - [error] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
node-red_1  |     at new NodeError (internal/errors.js:322:7)
node-red_1  |     at Socket.Writable.write (internal/streams/writable.js:294:11)
node-red_1  |     at KNXClient.send (/data/node_modules/node-red-contrib-knx-ultimate/KNXEngine/KNXClient.js:295:36)
node-red_1  |     at KNXClient._sendDisconnectRequestMessage (/data/node_modules/node-red-contrib-knx-ultimate/KNXEngine/KNXClient.js:1044:14)
node-red_1  |     at KNXClient.Disconnect (/data/node_modules/node-red-contrib-knx-ultimate/KNXEngine/KNXClient.js:704:14)
node-red_1  |     at knxUltimateConfigNode.node.Disconnect (/data/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:436:69)
node-red_1  |     at knxUltimateConfigNode.node.initKNXConnection (/data/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:715:22)
node-red_1  |     at Timeout._onTimeout (/data/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:1780:22)
node-red_1  |     at listOnTimeout (internal/timers.js:557:17)
node-red_1  |     at processTimers (internal/timers.js:500:7)
```

**To Reproduce**
Setup a KNX connection to a non working address.
Reboot Node-red

**Knx-Ultimate Version**
1.3.30

**Are you running node-red behind homematic, docker or anything similar?**
Docker-compose

**Comment by Supergiovane** [comment]
Hi
TCP is reserved for KNX Secure and is not yet implemented. Please use an unsecure connection via UDP.

**Comment by Supergiovane** [comment]
PS: look at the gateway config window. Select Tunnel UDP.

**Comment by Supergiovane** [comment]
Please let me know if it solved your issue. Thanks.

**Comment by martijndierckx** [comment]
Solved it indeed.
