### ISSUE TITLE
Error "malformed Header"

### ISSUE THREAD

**Issue by gtnscebba** [Supergiovane/node-red-contrib-knx-ultimate#376]
Hi Massimo,
as you know, I have been using your amazing KNXUltimate project for a long time.
These days, due to various problems with the Raspberry PI 4+ microSD I decided to do a clean installation.
I reinstalled everything and I am in this environment:

Raspberry PI 4b with 4 GB Ram
Linux 12 ( Debian 1:6.6.47-)
Node Red 4.0.4
NodeJS 20.17
KNXUltimate 3.2.4

All is running as expected, except for your palette.

Basically KNX Ultimate does not receive correct telegrams (he says):

```
Sep 17 18:07:01 PI4 Node-RED[1540]: 17/09/2024, 18:07:01 [KNXEngine] [ERROR] Received KNX packet: Error processing inbound message: Cannot read properties of undefined (reading 'length') Data received: 061004200018040485002900bce000ff1a00040080520701 srcAddress: {"address":"192.168.1.200","family":"IPv4","port":3671,"size":24} ChannelID:4 Host:192.168.1.200:3671. This means that KNX-Ultimate received a malformed Header or CEMI message from your KNX Gateway.
Sep 17 18:07:06 PI4 Node-RED[1540]: 17/09/2024, 18:07:06 [KNXEngine] [ERROR] Received KNX packet: Error processing inbound message: Cannot read properties of undefined (reading 'length') Data received: 061004200017040486002900bce011141005030080191f srcAddress: {"address":"192.168.1.200","family":"IPv4","port":3671,"size":23} ChannelID:4 Host:192.168.1.200:3671. This means that KNX-Ultimate received a malformed Header or CEMI message from your KNX Gateway
```

What I see on NR is (for example):

![image](https://github.com/user-attachments/assets/a3322d65-ebf9-4fc2-b8bb-ae119a233cad)

In other moment I see "READ" instead of "Writing".

I think that (maybe) is better that I install a previous version of KNX Ultimate, but I don't remember the correct procedure to do it: could you help me?

Thanks a lot!

Ciao!

**Comment by gtnscebba** [comment]
Other errors:

```
Sep 17 17:57:27 PI4 Node-RED[1540]: 17/09/2024, 17:57:27 [knxUltimate-config.js] [ERROR] knxUltimate-config: node.knxConnection.write: Payload: false GA:5/2/16 DPT:1.001 TypeError: Cannot read properties of undefined (reading 'length')
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimateViewer.node.createPayloadPIN3 (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimateViewer.js:160:32)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimateViewer.node.handleSend (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimateViewer.js:65:23)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at /home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:906:24
Sep 17 17:57:27 PI4 Node-RED[1540]:     at Array.forEach (<anonymous>)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at KNXClient.handleBusEvents (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:796:14)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at KNXClient.emit (node:events:519:28)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at KNXClient.write (/home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:678:10)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimateConfigNode.node.sendKNXTelegramToKNXEngine (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:1249:30)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimate._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate.js:565:30)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
Sep 17 17:57:27 PI4 Node-RED[1540]:     at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimate.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimate.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at knxUltimate.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:499:10)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at deliverMessageToDestination (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:803:40)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:819:21)
Sep 17 17:57:27 PI4 Node-RED[1540]:     at processImmediate (node:internal/timers:483:21)
```

I hope they are useful for you.

**Comment by Supergiovane** [comment]
Ho Gaetano
Thanks for the log. 
Just nagate into ./node-red folder and type 
npm install node-red-knx-ultimate@3.1.9
Thenrenoot

**Comment by Supergiovane** [comment]
Anyway, i've already catched the error and i'm fixing it right now.

**Comment by Supergiovane** [comment]
Fixed in node-red-contrib-knx-ultimate v. 3.2.5, out now.
Cheers.

**Comment by gtnscebba** [comment]
Thank you, Massimo.

I did what you suggested, but I got an error:

```
pi@PI4:~/.node-red $ npm install node-red-knx-ultimate@3.1.9
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/node-red-knx-ultimate - Not found
npm error 404
npm error 404  'node-red-knx-ultimate@3.1.9' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-09-17T18_29_54_083Z-debug-0.log
```

**Comment by gtnscebba** [comment]
Massimo,
I've installed 3.2.5 and seems to work correctly.

Many thanks for your very fast support

Ciao!
