### ISSUE TITLE
Connection Issue since updating to Node-Red v4.0.5

### ISSUE THREAD

**Issue by albertv0** [Supergiovane/node-red-contrib-knx-ultimate#391]
Hello,
I have recently updated Node-Red to V4 and the nodes are no longer connecting to the KNX IP gateway.
No other changes in the system. 
Do you know if there is any global setting needing change since the update to V4?

Thanks,
Albert

**Comment by Supergiovane** [comment]
Hi
Check this and set it to AUTO (in the gateway node config window)

<img width="563" alt="Node-RED___Avvio" src="https://github.com/user-attachments/assets/4d399c31-7d52-43f0-b96c-275de52691d3">

**Comment by albertv0** [comment]
Thanks for the quick response.
Already tried that.. connection keeps timing out.

**Comment by Supergiovane** [comment]
I need more info. Pease grab the debug text (there is a button in the "Utility" tab and post it here.

**Comment by albertv0** [comment]
Is this what you meant? I'm not sure it is containing the errors...
I can get you the terminal logs also.

<
-> id: f073b15335d3a937
-> _def: [object Object]
-> type: knxUltimate-config
-> z: 
-> users: [object Object]
-> host: 192.168.0.29
-> port: 3671
-> physAddr: 15.15.22
-> hostProtocol: Auto
-> KNXEthInterface: Auto
-> stopETSImportIfNoDatapoint: fake
-> loglevel: error
-> name: KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 25
-> autoReconnect: yes
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> infoEditor: [object Object]
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterfaceManuallyInput: 
-> ignoreTelegramsWithRepeatedFlag: false
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> valid: true
-> validationErrors: 
-> dirty: true
-> changed: false
-> credentials: [object Object]

>

ENOENT: no such file or directory, open './KNXUltimateDebugLog.txt'

**Comment by Supergiovane** [comment]
Hi
have you updated knxultimate to the latest version? If not, please do it, then restart node-red-
If unsuccessful, i need to know why it doesn't connect, so i need you to paste the log here.

**Comment by Supergiovane** [comment]
Hi
`handleKNXQueue: Start Processing queued KNX` means, that's connected to the KNX IP Gateway.
I see you're under Docker. In the gateway config window, you should set the interface used by docker to connect to your lan.
The "Auto" setting may not be accurate in your case, but as i wrote, the node seems connected to the BUS. 
Have you ETS to test with?

**Comment by albertv0** [comment]
I also thought about some issue with the Docker host.
I tried eth0, below is the log.
To rule out any issue related to docker, I also installed Node-Red temporarily in the PC to try there. Seems there I am struggling to find a suitable intereface to connect to LAN.. will keep investigating that issue.

2024-10-24T11:41:58 at KNXClient.closeSocket (/data/node_modules/knxultimate/build/KNXClient.js:640:16)

2024-10-24T11:41:58 at KNXClient.setDisconnected (/data/node_modules/knxultimate/build/KNXClient.js:696:20)

2024-10-24T11:41:58 at KNXClient.processInboundMessage (/data/node_modules/knxultimate/build/KNXClient.js:789:30)

2024-10-24T11:41:58 at Socket.emit (node:events:519:28)

2024-10-24T11:41:58 at UDP.onMessage [as onmessage] (node:dgram:946:8)

2024-10-24T11:42:04 10/24/2024, 9:42:04 AM [KNXEngine] [ERROR] KNXClient: into async closeSocket(): Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

2024-10-24T11:42:04 at healthCheck (node:dgram:924:11)

2024-10-24T11:42:04 at Socket.close (node:dgram:749:3)

2024-10-24T11:42:04 at /data/node_modules/knxultimate/build/KNXClient.js:654:40

2024-10-24T11:42:04 at new Promise (<anonymous>)

2024-10-24T11:42:04 at KNXClient.closeSocket (/data/node_modules/knxultimate/build/KNXClient.js:640:16)

2024-10-24T11:42:04 at KNXClient.Disconnect (/data/node_modules/knxultimate/build/KNXClient.js:676:24)

**Comment by Supergiovane** [comment]
Hi
If you've some switch/router between your PC and the KNX IP Gateway, make sure UDP isn't blocked. KNX uses UDP packets; some switches (for example Ubiquiti ones), filter some UDP traffic.

**Comment by albertv0** [comment]
I have unmanaged switches. The router managing my LAN with both PC and KNX IP gateway is indeed Ubiquiti.
But would it make sense that it stopped working now since udating to Node-Red V4? It was working fine yesterday before the upgrade.

**Comment by Supergiovane** [comment]
I don't know wether node-red installation script, updates nodejs version as well.
Please do a **node -v** command in the terminal and write the result.

**Comment by albertv0** [comment]
node -v
v20.18.0

**Comment by albertv0** [comment]
Pinging 192.168.0.29 with 32 bytes of data:
Reply from 192.168.0.29: bytes=32 time=2ms TTL=64
Reply from 192.168.0.29: bytes=32 time=2ms TTL=64
Reply from 192.168.0.29: bytes=32 time=10ms TTL=64
Reply from 192.168.0.29: bytes=32 time=25ms TTL=64

Ping statistics for 192.168.0.29:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 25ms, Average = 9ms

**Comment by Supergiovane** [comment]
Ok, you should connect. There is nothing wrong. Let's see if the KNX IP Gateway has reached the maximum allowed connection. I need you to set the log to "debug", restart node-red and after a while, i need you to send here the log. Please paste it into the <> brackets, so i can read it more flawlessly :-)

**Comment by albertv0** [comment]
just to confirm, the log from the terminal?

**Comment by Supergiovane** [comment]
Yes.

**Comment by Supergiovane** [comment]
But longer than the previous.

**Comment by albertv0** [comment]
`2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) docker0 {"address":"fe80::42:78ff:feb1:8d02","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"02:42:78:b1:8d:02","internal":false,"cidr":"fe80::42:78ff:feb1:8d02/64","scopeid":5}[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) vetha0c163a {"address":"169.254.61.193","netmask":"255.255.0.0","family":"IPv4","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"169.254.61.193/16"}[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found suitable interface: %s (%j) vetha0c163a {"address":"169.254.61.193","netmask":"255.255.0.0","family":"IPv4","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"169.254.61.193/16"}[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) vetha0c163a {"address":"fe80::2c40:59ff:fecb:c134","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"fe80::2c40:59ff:fecb:c134/64","scopeid":7}[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) vetha0c163a {"address":"fe80::2c40:59ff:fecb:c134","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"fe80::2c40:59ff:fecb:c134/64","scopeid":7}[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [knxUltimate-config <KNX Gateway>] [42m[30m[INFO][0m [32mperform websocket connection on KNX Gateway[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [knxUltimate-config <KNX Gateway>] [42m[30m[INFO][0m [32mConnecting... KNX Gateway[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mConnecting to192.168.0.29[0m

2024-10-24T13:30:13 10/24/2024, 11:30:13 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: handleKNXQueue: Start Processing queued KNX.[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: ADDED TELEGRAM TO COMMANDQUEUE. Len: 1, Priority: true {"knxPacket":{"type":517,"length":20,"_header":{"_headerLength":6,"_version":16,"service_type":517,"length":26},"cri":{"_connectionType":4,"knxLayer":2},"hpaiControl":{"_port":0,"_protocol":1,"_host":"0.0.0.0","_splitHost":["0.0.0.0","0","0","0","0"]},"hpaiData":{"_port":0,"_protocol":1,"_host":"0.0.0.0","_splitHost":["0.0.0.0","0","0","0","0"]}},"expectedSeqNumberForACK":-1}[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: processKnxPacketQueueItem: Processing queued KNX. commandQueue.length: 0 517[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [46m[30m[DEBUG][0m [36mSending KNX packet: KNXConnectRequest Host:192.168.0.29:3671[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [46m[30m[DEBUG][0m [36mReceived KNX packet: _processInboundMessage, Data received: 0610020600140b24080100000000000004041133 srcAddress: {"address":"192.168.0.29","family":"IPv4","port":3671,"size":20} ChannelID:null[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [41m[ERROR][0m [31mError: No More Connections

2024-10-24T13:30:15     at KNXClient.processInboundMessage (/data/node_modules/knxultimate/build/KNXClient.js:788:58)

2024-10-24T13:30:15     at Socket.emit (node:events:519:28)

2024-10-24T13:30:15     at UDP.onMessage [as onmessage] (node:dgram:946:8)[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [knxUltimate-config <KNX Gateway>] [41m[ERROR][0m [31mreceived KNXClientEvents.error: No More Connections[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: into Disconnect(), channel id is not defined so skip disconnect packet and close socket[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [knxUltimate-config <KNX Gateway>] [41m[ERROR][0m [31mDisconnected by: No More Connections[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: called _setDisconnected 192.168.0.29:3671 Connect response error 36[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [KNXEngine] [41m[ERROR][0m [31mKNXClient: into async closeSocket(): Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

2024-10-24T13:30:15     at healthCheck (node:dgram:924:11)

2024-10-24T13:30:15     at Socket.close (node:dgram:749:3)

2024-10-24T13:30:15     at /data/node_modules/knxultimate/build/KNXClient.js:654:40

2024-10-24T13:30:15     at new Promise (<anonymous>)

2024-10-24T13:30:15     at KNXClient.closeSocket (/data/node_modules/knxultimate/build/KNXClient.js:640:16)

2024-10-24T13:30:15     at KNXClient.setDisconnected (/data/node_modules/knxultimate/build/KNXClient.js:696:20)

2024-10-24T13:30:15     at KNXClient.processInboundMessage (/data/node_modules/knxultimate/build/KNXClient.js:789:30)

2024-10-24T13:30:15     at Socket.emit (node:events:519:28)

2024-10-24T13:30:15     at UDP.onMessage [as onmessage] (node:dgram:946:8)[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mKNXClient socket closed.[0m

2024-10-24T13:30:15 10/24/2024, 11:30:15 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mDisconnected, node.autoReconnect:true[0m

2024-10-24T13:30:17 10/24/2024, 11:30:17 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mWaiting next cycle to reconect. node.LinkStatus: disconnected, node.autoReconnect:true[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mAuto Reconect by timerKNXUltimateCheckState in progress. node.LinkStatus: disconnected, node.autoReconnect:true[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [42m[30m[INFO][0m [32mBind KNX Bus to interface : eth0 (Interface's name entered by hand). Node KNX Gateway[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mDisconnect: already not connected:disconnected, node.autoReconnect:true[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: into Disconnect(), channel id is not defined so skip disconnect packet and close socket[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [41m[ERROR][0m [31mKNXClient: into async closeSocket(): Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

2024-10-24T13:30:21     at healthCheck (node:dgram:924:11)

2024-10-24T13:30:21     at Socket.close (node:dgram:749:3)

2024-10-24T13:30:21     at /data/node_modules/knxultimate/build/KNXClient.js:654:40

2024-10-24T13:30:21     at new Promise (<anonymous>)

2024-10-24T13:30:21     at KNXClient.closeSocket (/data/node_modules/knxultimate/build/KNXClient.js:640:16)

2024-10-24T13:30:21     at KNXClient.Disconnect (/data/node_modules/knxultimate/build/KNXClient.js:676:24)

2024-10-24T13:30:21     at node.initKNXConnection (/data/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:618:38)

2024-10-24T13:30:21     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mremoving old handlers. Node KNX Gateway[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: getLocalAddress: getting interfaces[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) lo {"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true,"cidr":"127.0.0.1/8"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) lo {"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true,"cidr":"127.0.0.1/8"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) lo {"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","internal":true,"cidr":"::1/128","scopeid":0}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) lo {"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","internal":true,"cidr":"::1/128","scopeid":0}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) dummy0 {"address":"169.254.36.22","netmask":"255.255.0.0","family":"IPv4","mac":"72:a5:0f:40:a1:7a","internal":false,"cidr":"169.254.36.22/16"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found suitable interface: %s (%j) dummy0 {"address":"169.254.36.22","netmask":"255.255.0.0","family":"IPv4","mac":"72:a5:0f:40:a1:7a","internal":false,"cidr":"169.254.36.22/16"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) dummy0 {"address":"fe80::6897:63b7:69b9:f425","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"72:a5:0f:40:a1:7a","internal":false,"cidr":"fe80::6897:63b7:69b9:f425/64","scopeid":2}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) dummy0 {"address":"fe80::6897:63b7:69b9:f425","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"72:a5:0f:40:a1:7a","internal":false,"cidr":"fe80::6897:63b7:69b9:f425/64","scopeid":2}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) eth0 {"address":"192.168.0.203","netmask":"255.255.255.0","family":"IPv4","mac":"d0:27:03:46:1f:b0","internal":false,"cidr":"192.168.0.203/24"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found suitable interface: %s (%j) eth0 {"address":"192.168.0.203","netmask":"255.255.255.0","family":"IPv4","mac":"d0:27:03:46:1f:b0","internal":false,"cidr":"192.168.0.203/24"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) eth0 {"address":"fd02:2dd5:1ae7:7449:48db:c0a4:80d0:3d18","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"d0:27:03:46:1f:b0","internal":false,"cidr":"fd02:2dd5:1ae7:7449:48db:c0a4:80d0:3d18/64","scopeid":0}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) eth0 {"address":"fd02:2dd5:1ae7:7449:48db:c0a4:80d0:3d18","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"d0:27:03:46:1f:b0","internal":false,"cidr":"fd02:2dd5:1ae7:7449:48db:c0a4:80d0:3d18/64","scopeid":0}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) eth0 {"address":"fe80::1a67:9c17:8725:eb08","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"d0:27:03:46:1f:b0","internal":false,"cidr":"fe80::1a67:9c17:8725:eb08/64","scopeid":3}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) eth0 {"address":"fe80::1a67:9c17:8725:eb08","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"d0:27:03:46:1f:b0","internal":false,"cidr":"fe80::1a67:9c17:8725:eb08/64","scopeid":3}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) docker0 {"address":"172.17.0.1","netmask":"255.255.0.0","family":"IPv4","mac":"02:42:78:b1:8d:02","internal":false,"cidr":"172.17.0.1/16"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found suitable interface: %s (%j) docker0 {"address":"172.17.0.1","netmask":"255.255.0.0","family":"IPv4","mac":"02:42:78:b1:8d:02","internal":false,"cidr":"172.17.0.1/16"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) docker0 {"address":"fe80::42:78ff:feb1:8d02","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"02:42:78:b1:8d:02","internal":false,"cidr":"fe80::42:78ff:feb1:8d02/64","scopeid":5}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) docker0 {"address":"fe80::42:78ff:feb1:8d02","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"02:42:78:b1:8d:02","internal":false,"cidr":"fe80::42:78ff:feb1:8d02/64","scopeid":5}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) vetha0c163a {"address":"169.254.61.193","netmask":"255.255.0.0","family":"IPv4","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"169.254.61.193/16"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found suitable interface: %s (%j) vetha0c163a {"address":"169.254.61.193","netmask":"255.255.0.0","family":"IPv4","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"169.254.61.193/16"}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: parsing interface: %s (%j) vetha0c163a {"address":"fe80::2c40:59ff:fecb:c134","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"fe80::2c40:59ff:fecb:c134/64","scopeid":7}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mipAddressHelper.js: Found NOT suitable interface: %s (%j) vetha0c163a {"address":"fe80::2c40:59ff:fecb:c134","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"2e:40:59:cb:c1:34","internal":false,"cidr":"fe80::2c40:59ff:fecb:c134/64","scopeid":7}[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [42m[30m[INFO][0m [32mperform websocket connection on KNX Gateway[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [42m[30m[INFO][0m [32mConnecting... KNX Gateway[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mConnecting to192.168.0.29[0m

2024-10-24T13:30:21 10/24/2024, 11:30:21 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: handleKNXQueue: Start Processing queued KNX.[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: ADDED TELEGRAM TO COMMANDQUEUE. Len: 1, Priority: true {"knxPacket":{"type":517,"length":20,"_header":{"_headerLength":6,"_version":16,"service_type":517,"length":26},"cri":{"_connectionType":4,"knxLayer":2},"hpaiControl":{"_port":0,"_protocol":1,"_host":"0.0.0.0","_splitHost":["0.0.0.0","0","0","0","0"]},"hpaiData":{"_port":0,"_protocol":1,"_host":"0.0.0.0","_splitHost":["0.0.0.0","0","0","0","0"]}},"expectedSeqNumberForACK":-1}[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: processKnxPacketQueueItem: Processing queued KNX. commandQueue.length: 0 517[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [46m[30m[DEBUG][0m [36mSending KNX packet: KNXConnectRequest Host:192.168.0.29:3671[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [46m[30m[DEBUG][0m [36mReceived KNX packet: _processInboundMessage, Data received: 0610020600140b24080100000000000004041133 srcAddress: {"address":"192.168.0.29","family":"IPv4","port":3671,"size":20} ChannelID:null[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [41m[ERROR][0m [31mError: No More Connections

2024-10-24T13:30:23     at KNXClient.processInboundMessage (/data/node_modules/knxultimate/build/KNXClient.js:788:58)

2024-10-24T13:30:23     at Socket.emit (node:events:519:28)

2024-10-24T13:30:23     at UDP.onMessage [as onmessage] (node:dgram:946:8)[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [knxUltimate-config <KNX Gateway>] [41m[ERROR][0m [31mreceived KNXClientEvents.error: No More Connections[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: into Disconnect(), channel id is not defined so skip disconnect packet and close socket[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [knxUltimate-config <KNX Gateway>] [41m[ERROR][0m [31mDisconnected by: No More Connections[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [46m[30m[DEBUG][0m [36mKNXClient: called _setDisconnected 192.168.0.29:3671 Connect response error 36[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [KNXEngine] [41m[ERROR][0m [31mKNXClient: into async closeSocket(): Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

2024-10-24T13:30:23     at healthCheck (node:dgram:924:11)

2024-10-24T13:30:23     at Socket.close (node:dgram:749:3)

2024-10-24T13:30:23     at /data/node_modules/knxultimate/build/KNXClient.js:654:40

2024-10-24T13:30:23     at new Promise (<anonymous>)

2024-10-24T13:30:23     at KNXClient.closeSocket (/data/node_modules/knxultimate/build/KNXClient.js:640:16)

2024-10-24T13:30:23     at KNXClient.setDisconnected (/data/node_modules/knxultimate/build/KNXClient.js:696:20)

2024-10-24T13:30:23     at KNXClient.processInboundMessage (/data/node_modules/knxultimate/build/KNXClient.js:789:30)

2024-10-24T13:30:23     at Socket.emit (node:events:519:28)

2024-10-24T13:30:23     at UDP.onMessage [as onmessage] (node:dgram:946:8)[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mKNXClient socket closed.[0m

2024-10-24T13:30:23 10/24/2024, 11:30:23 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mDisconnected, node.autoReconnect:true[0m

2024-10-24T13:30:25 10/24/2024, 11:30:25 AM [knxUltimate-config <KNX Gateway>] [46m[30m[DEBUG][0m [36mWaiting next cycle to reconect. node.LinkStatus: disconnected, node.autoReconnect:true[0m
`

**Comment by Supergiovane** [comment]
`

Error: No More Connections

`

The KNX/IP gateway has no more free tunnels.
Please restart or unplug/replug, the KNX IP Interface to free the tunnels.

**Comment by albertv0** [comment]
OMG. That was it!
I am really sorry for taking your time today. Thank you so much!

**Comment by Supergiovane** [comment]
You're wellcome!
