### ISSUE TITLE
BUS very slow after upgrade

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#393]
Hi!
With this issue I'm continuing #378 because I cannot reopen as it was marked as "completed".

I had time only today for trying the config suggested and do some tests, but it was not the soution.
I tried: 30, 50, 100, 300, 500, 800 and... 0 but the behaviour remains the same: I see telegrams running on the node state but only a small pecentage are coming on the bus log, ETS Diagnosys side.
So the issue is that only about 3% is leaving node-red and sent to the KNX IP Tunnel.
Of course, I can't let the house stay in this condition, so I must downgrade to 3.1.9 after the test.
For this reason, please don't close in a definitive way ("completed") this issue without my confirmation (this should be a general rule :blush:) or I won't be able to reopen it and I'll be forced to open a new one.

What kind of tests should I start for investingating the issue?

Here my configs:
Node Red: 4.0.5
npm: 10.9.0
NodeJS: 22.11.0
(Issue happened with previos versions of NR and NJS, too.)

![1](https://github.com/user-attachments/assets/f4451b92-eb36-4a48-988f-d84eded5f154)
![2](https://github.com/user-attachments/assets/d3c0d2b3-ee76-4832-8507-dd3b777af591)
![3](https://github.com/user-attachments/assets/aa1ed7e7-3401-4a7a-86e2-992ef6df33f9)
![4](https://github.com/user-attachments/assets/2d6493fc-e232-44c7-b106-9d1b0014850b)

**Comment by Supergiovane** [comment]
Hi
What version of KNX Ultimate are you using now?

**Comment by Supergiovane** [comment]
Hi!
Please put the content of the zip file, into your .node-red/node_modules/node-red-contrib-knx-ultimate/nodes folder and restart node-red.
Then let it run for a while and let me know.
Thanks.

[Archivio.zip](https://github.com/user-attachments/files/17704539/Archivio.zip)

**Comment by Supergiovane** [comment]
PS: **prior to do that, please update to the latest version of knx-ultimate!**
Only after, unzip the file by replacing the files in that folder.

**Comment by Supergiovane** [comment]
Hi Enrico
have you checked if it works?

**Comment by evazzoler** [comment]
Not yet. Sorry.
(to much busy with job)

Il 15 novembre 2024 10:11:46 CET, Massimo Saccani ***@***.***> ha scritto:

**Comment by Supergiovane** [comment]
Hi
Any news?

**Comment by Supergiovane** [comment]
You can update ti the latest version. It contains some mods.

**Comment by PrimaLuceEnrico** [comment]
Finally the module arrived and I've changed it today. Hours to "dd" in and out the eMMC via waveshare CM module...

Unfortunately the upgrade of KNX-Ultimate goes wrong with this error:

`2025-04-25T14:37:14.351Z Install : node-red-contrib-knx-ultimate 3.3.32

2025-04-25T14:37:14.374Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-knx-ultimate@3.3.32
2025-04-25T14:37:26.641Z [err] npm error code EACCES
2025-04-25T14:37:26.642Z [err] npm error syscall rename
2025-04-25T14:37:26.643Z [err] npm error path /home/pi/.node-red/node_modules/.knxultimate-UNQd9CZy/node_modules/xml2js/LICENSE
2025-04-25T14:37:26.643Z [err] npm error dest /home/pi/.node-red/node_modules/knxultimate/node_modules/xml2js/LICENSE
2025-04-25T14:37:26.643Z [err] npm error errno -13
2025-04-25T14:37:26.646Z [err] npm error Error: EACCES: permission denied, rename '/home/pi/.node-red/node_modules/.knxultimate-UNQd9CZy/node_modules/xml2js/LICENSE' -> '/home/pi/.node-red/node_modules/knxultimate/node_modules/xml2js/LICENSE'
2025-04-25T14:37:26.646Z [err] npm error     at async Object.rename (node:internal/fs/promises:783:10)
2025-04-25T14:37:26.646Z [err] npm error     at async moveFile (/usr/local/lib/node_modules/npm/node_modules/@npmcli/fs/lib/move-file.js:30:5)
2025-04-25T14:37:26.646Z [err] npm error     at async Promise.allSettled (index 0)
2025-04-25T14:37:26.646Z [err] npm error     at async Promise.allSettled (index 0)
2025-04-25T14:37:26.646Z [err] npm error     at async Promise.allSettled (index 2)
2025-04-25T14:37:26.646Z [err] npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
2025-04-25T14:37:26.646Z [err] npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
2025-04-25T14:37:26.646Z [err] npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
2025-04-25T14:37:26.646Z [err] npm error     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
2025-04-25T14:37:26.646Z [err] npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
2025-04-25T14:37:26.646Z [err] npm error   errno: -13,
2025-04-25T14:37:26.646Z [err] npm error   code: 'EACCES',
2025-04-25T14:37:26.646Z [err] npm error   syscall: 'rename',
2025-04-25T14:37:26.646Z [err] npm error   path: '/home/pi/.node-red/node_modules/.knxultimate-UNQd9CZy/node_modules/xml2js/LICENSE',
2025-04-25T14:37:26.646Z [err] npm error   dest: '/home/pi/.node-red/node_modules/knxultimate/node_modules/xml2js/LICENSE'
2025-04-25T14:37:26.646Z [err] npm error }
2025-04-25T14:37:26.647Z [err] npm error
2025-04-25T14:37:26.647Z [err] npm error The operation was rejected by your operating system.
2025-04-25T14:37:26.647Z [err] npm error It is likely you do not have the permissions to access this file as the current user
2025-04-25T14:37:26.647Z [err] npm error
2025-04-25T14:37:26.647Z [err] npm error If you believe this might be a permissions issue, please double-check the
2025-04-25T14:37:26.647Z [err] npm error permissions of the file and its containing directories, or try running
2025-04-25T14:37:26.647Z [err] npm error the command again as root/Administrator.
2025-04-25T14:37:26.652Z [err] npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2025-04-25T14_37_14_658Z-debug-0.log
2025-04-25T14:37:26.683Z rc=243`

Any idea?

**Comment by evazzoler** [comment]
Finally the module arrived and I've changed it today. Hours to "dd" in and out the eMMC via waveshare CM module...

Unfortunately the upgrade of KNX-Ultimate goes wrong with this error:


```
2025-04-25T14:37:14.351Z Install : node-red-contrib-knx-ultimate 3.3.32

2025-04-25T14:37:14.374Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-knx-ultimate@3.3.32
2025-04-25T14:37:26.641Z [err] npm error code EACCES
2025-04-25T14:37:26.642Z [err] npm error syscall rename
2025-04-25T14:37:26.643Z [err] npm error path /home/pi/.node-red/node_modules/.knxultimate-UNQd9CZy/node_modules/xml2js/LICENSE
2025-04-25T14:37:26.643Z [err] npm error dest /home/pi/.node-red/node_modules/knxultimate/node_modules/xml2js/LICENSE
2025-04-25T14:37:26.643Z [err] npm error errno -13
2025-04-25T14:37:26.646Z [err] npm error Error: EACCES: permission denied, rename '/home/pi/.node-red/node_modules/.knxultimate-UNQd9CZy/node_modules/xml2js/LICENSE' -> '/home/pi/.node-red/node_modules/knxultimate/node_modules/xml2js/LICENSE'
2025-04-25T14:37:26.646Z [err] npm error at async Object.rename (node:internal/fs/promises:783:10)
2025-04-25T14:37:26.646Z [err] npm error at async moveFile (/usr/local/lib/node_modules/npm/node_modules/@npmcli/fs/lib/move-file.js:30:5)
2025-04-25T14:37:26.646Z [err] npm error at async Promise.allSettled (index 0)
2025-04-25T14:37:26.646Z [err] npm error at async Promise.allSettled (index 0)
2025-04-25T14:37:26.646Z [err] npm error at async Promise.allSettled (index 2)
2025-04-25T14:37:26.646Z [err] npm error at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
2025-04-25T14:37:26.646Z [err] npm error at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
2025-04-25T14:37:26.646Z [err] npm error at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
2025-04-25T14:37:26.646Z [err] npm error at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
2025-04-25T14:37:26.646Z [err] npm error at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
2025-04-25T14:37:26.646Z [err] npm error errno: -13,
2025-04-25T14:37:26.646Z [err] npm error code: 'EACCES',
2025-04-25T14:37:26.646Z [err] npm error syscall: 'rename',
2025-04-25T14:37:26.646Z [err] npm error path: '/home/pi/.node-red/node_modules/.knxultimate-UNQd9CZy/node_modules/xml2js/LICENSE',
2025-04-25T14:37:26.646Z [err] npm error dest: '/home/pi/.node-red/node_modules/knxultimate/node_modules/xml2js/LICENSE'
2025-04-25T14:37:26.646Z [err] npm error }
2025-04-25T14:37:26.647Z [err] npm error
2025-04-25T14:37:26.647Z [err] npm error The operation was rejected by your operating system.
2025-04-25T14:37:26.647Z [err] npm error It is likely you do not have the permissions to access this file as the current user
2025-04-25T14:37:26.647Z [err] npm error
2025-04-25T14:37:26.647Z [err] npm error If you believe this might be a permissions issue, please double-check the
2025-04-25T14:37:26.647Z [err] npm error permissions of the file and its containing directories, or try running
2025-04-25T14:37:26.647Z [err] npm error the command again as root/Administrator.
2025-04-25T14:37:26.652Z [err] npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2025-04-25T14_37_14_658Z-debug-0.log
2025-04-25T14:37:26.683Z rc=243
```


Any idea?
